#!/bin/sh

mkdir -p opk
cp ./game.elf opk/
cp ./icon.png opk/icon.png
cp -r data opk/data
rm opk/data/config/controls.cfg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'keyboard:1
SET_KEY:UP:273
SET_KEY:DOWN:274
SET_KEY:LEFT:276
SET_KEY:RIGHT:275
SET_KEY:A:306
SET_KEY:B:308
SET_KEY:START:13
SET_KEY:SELECT:27
#joystick
joypad:1
SET_BUTTON:UP:255
SET_BUTTON:DOWN:255
SET_BUTTON:LEFT:255
SET_BUTTON:RIGHT:255
SET_BUTTON:A:4
SET_BUTTON:B:5
SET_BUTTON:START:6
SET_BUTTON:SELECT:303
SET_AXIS:X:0
SET_AXIS:Y:1
AXIS_THRESHOLD:16383' > opk/data/config/controls.cfg

print '[Desktop Entry]
Type=Application
Name=Overheated
Comment=Shoot them up
Exec=game.elf
Icon=icon
Terminal=false
Type=Application
Categories=games;
' > opk/default."$1".desktop

mksquashfs ./opk overheated_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
