    //WAVE 0
    {
        { &spawnMediumExplosion_1 , { 16, 32, 00, 00}},
        { &spawnSmallExplosion_1  , {  0,  0, 00, 00}},
        { &spawnSmallExplosion_1  , { 10, 32, 00, 00}},
        { NULL , { 00, 00, 00, 00}}
        
    },
    //WAVE 1
    {
        { &spawnMediumExplosion_1 , { 32,  0, 00, 00}},
        { &spawnSmallExplosion_1  , {  0,  0, 00, 00}},
        { &spawnSmallExplosion_1  , { 10, 32, 00, 00}},
        { NULL , { 00, 00, 00, 00}}
    },
    //WAVE 2
    {
        { &spawnMediumExplosion_1 , {  0,  0, 00, 00}},
        { &spawnSmallExplosion_1  , { 32,  0, 00, 00}},
        { &spawnSmallExplosion_1  , { 28, 32, 00, 00}},
        { NULL , { 00, 00, 00, 00}}
    }
